# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: true

cran: https://cran.rstudio.com

# until generics is finalized
warnings_are_errors: false

r:
  - 3.5
  - 3.6
  - devel

# - devel  # massive failures, not sure why yet

cache:
  packages: true

after_success:
  - Rscript -e 'covr::codecov()'

